project_id = "vwumcbgtvqhnpioenagm"

[functions.crypto]
verify_jwt = false

[functions.check-login-attempt]
verify_jwt = false

[functions.create-seller]
verify_jwt = true

[functions.change-seller-password]
verify_jwt = true

[functions.generate-temp-password]
verify_jwt = false

[functions.backup-data]
verify_jwt = false

[functions.restore-data]
verify_jwt = false

[functions.cleanup-trash]
verify_jwt = true

[functions.generate-server-icon]
verify_jwt = true

[functions.generate-vapid-keys]
verify_jwt = true

[functions.save-push-subscription]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.check-expirations]
verify_jwt = false
